import {CONNECTIONS_CONFIG, ICON_DRAW_CONFIG, PLATFORM_MARKER_CONFIG} from '../constants';

export const {BG_PADDING_RATIO, BG_RADIUS_RATIO, ICON_DRAW_RATIO} = ICON_DRAW_CONFIG;

export const {
    LINE_DURATION: CONNECTIONS_LINE_DURATION,
    LINE_WIDTH_RATIO: CONNECTION_LINE_WIDTH_RATIO,
    DOT_RADIUS_RATIO: CONNECTION_DOT_RADIUS_RATIO,
    COLOR: CONNECTION_COLOR,
    HIGHLIGHT_COLOR: CONNECTION_HIGHLIGHT_COLOR,
    TEXT_ANCHOR_GAP_RATIO: CONNECTION_TEXT_ANCHOR_GAP_RATIO,
    SERPENTINE: {
        TURNS: SERPENTINE_TURNS,
        AMPLITUDE_RATIO: SERPENTINE_AMPLITUDE_RATIO,
        STRAIGHT_FRACTION: SERPENTINE_STRAIGHT_FRACTION,
    },
    SCHEME_SERPENTINE: {
        TURNS: SCHEME_SERPENTINE_TURNS,
        AMPLITUDE_RATIO: SCHEME_SERPENTINE_AMPLITUDE_RATIO,
        STRAIGHT_FRACTION: SCHEME_SERPENTINE_STRAIGHT_FRACTION,
        CORNER_RADIUS_RATIO: SCHEME_SERPENTINE_CORNER_RADIUS_RATIO,
        CORNER_SEGMENTS: SCHEME_SERPENTINE_CORNER_SEGMENTS,
    },
    ARC: {BULGE_RATIO: ARC_BULGE_RATIO, SEGMENTS: ARC_SEGMENTS},
    SCHEME_ARC: {BULGE_RATIO: SCHEME_ARC_BULGE_RATIO, SEGMENTS: SCHEME_ARC_SEGMENTS},
    DASH: {LENGTH_RATIO: DASH_LENGTH_RATIO, GAP_RATIO: DASH_GAP_RATIO},
} = CONNECTIONS_CONFIG;

export const {
    LENGTH_RATIO: MARKER_LENGTH_RATIO,
    BOTTOM_OFFSET_RATIO: MARKER_BOTTOM_OFFSET_RATIO,
    LINE_WIDTH_RATIO: MARKER_LINE_WIDTH_RATIO,
    DOT_RADIUS_RATIO: MARKER_DOT_RADIUS_RATIO,
    COLOR: MARKER_COLOR,
} = PLATFORM_MARKER_CONFIG;
